# Generated by Django 4.2.27 on 2025-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=1, help_text='Time allowed for this question in minutes'),
        ),
    ]
