# Generated by Django 4.2.27 on 2025-12-29 05:10

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """Create default MCQ categories"""
    Category = apps.get_model('quiz_app', 'Category')
    
    categories = [
        {'name': 'Java', 'description': 'Java programming language MCQs'},
        {'name': 'Python', 'description': 'Python programming language MCQs'},
        {'name': 'DevOps', 'description': 'DevOps and infrastructure MCQs'},
        {'name': 'Power BI', 'description': 'Power BI and data visualization MCQs'},
    ]
    
    for cat_data in categories:
        Category.objects.get_or_create(
            name=cat_data['name'],
            defaults={'description': cat_data['description']}
        )


def reverse_create_default_categories(apps, schema_editor):
    """Reverse migration - delete default categories"""
    Category = apps.get_model('quiz_app', 'Category')
    Category.objects.filter(name__in=['Java', 'Python', 'DevOps', 'Power BI']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_category_userprofile_quiz_category'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_create_default_categories),
    ]
